---
- name: Exercise for setting up a web server in an EC2
  hosts: all
  #vars:
  #  - ansible_host_key_checking: false
  user: ubuntu
  roles:
    - setup


#  To add ec2 instances, run the code below.
#aws ec2 describe-instances \
#--query 'Reservations[*].Instances[*].PrivateIpAddress' \
#--filters "Name=tag:project,Values=udacity" \
#--output text >> inventory
