Resources:
  PrometheusEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: aws-udacity
      ImageId: "ami-0767046d1677be5a0"
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "Prometheus Instance"

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 9090
        ToPort: 9090
        CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 9100
        ToPort: 9100
        CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 9093
        ToPort: 9093
        CidrIp: 0.0.0.0/0
      

