Resources:
  PrometheusEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
        - sg-0677c128d2e2c2a9e
      KeyName: aws-udacity
      ImageId: "ami-0767046d1677be5a0"
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "Prometheus Instance"


      

