# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Print Hello 
          command: |
            #!/bin/bash
            chmod +x hello.sh
            ./hello.sh
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - run:
          name: Print World
          command: |
            #!/bin/bash
            chmod +x world.sh
            ./world.sh
  
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
      - run:
        name: Create Infrastructure with CloudFormation
        command: |
          aws cloudformation create-stack --stack-name CircleCI -template-body template.yml


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world
        requires:
          - print_hello