---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Install Prometheus
  become: yes
  command: |
    sudo useradd --no-create-home prometheus
    sudo mkdir /etc/prometheus
    sudo mkdir /var/lib/prometheus
    wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    tar xvfz prometheus-2.19.0.linux-amd64.tar.gz
    sudo cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
    sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    sudo cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
    sudo cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus
    sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64

- name: Create Prometheus.yml
  become: yes
  file: 
    path: /etc/prometheus/prometheus.yml
    state: touch
    owner: root
    group: root
    mode: 0600

- name: Create Content of Prometheus.yml
  become: yes
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
        external_labels:
          monitor: 'prometheus'
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

- name: Create Prometheus Service File
  become: true
  file: 
    path: /etc/systemd/system/prometheus.service
    state: touch
    owner: root
    group: root
    mode: 0600

- name: Create Content of Prometheus Service File
  become: yes
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries
      [Install]
      WantedBy=multi-user.target

- name: Change Permissions of prometheus yml and service files
  become: true
  command: |
    sudo chown prometheus:prometheus /etc/prometheus
    sudo chown prometheus:prometheus /usr/local/bin/prometheus
    sudo chown prometheus:prometheus /usr/local/bin/promtool
    sudo chown -R prometheus:prometheus /etc/prometheus/consoles
    sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
    sudo chown -R prometheus:prometheus /var/lib/prometheus
  
- name: Start Prometheus
  become: true
  command: |
    sudo systemctl daemon-reload
    sudo systemctl enable prometheus

